spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodtest?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring:
#  datasource:
#    url: jdbc:mysql://database-1.cnnqb3glnnoa.ap-northeast-2.rds.amazonaws.com/teamkimfood
#    username: admin
#    password: admin1234
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
      # 프로젝트 시작시 create로 두시고 진행중엔 none나 validate로 해주세요
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        # 해당 설정이 없다면 나중에 여러개 저장되어있는 db정보를 쿼리 1개씩 날림
    database-platform: org.hibernate.dialect.MySQLDialect

oauth:
  kakao:
    client-id: 69445a05dee5a6928649b416c9df1964
    client-secret: hxEg8JGhjQm7Np8bMd18vQWZhVOjcPm0
    redirect-uri: http://localhost:8080/login/oauth2/code/kakao
    oauth-url: https://kauth.kakao.com
    api-url: https://kapi.kakao.com

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

recipeImgLocation: c:/recipe/images

server:
  servlet:
    encoding:
      charset: UTF-8

jwt:
  secret_key: B1kt5JCu4ccayt2zYtmVB0XjUsZdV6jzFVB8RircuMJF9e09uO3vlqnlctxcLMVMjH